# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xcmg/workspace_cwx/front-stitcher

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xcmg/workspace_cwx/front-stitcher

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/xcmg/workspace_cwx/front-stitcher && $(CMAKE_COMMAND) -E cmake_progress_start /home/xcmg/workspace_cwx/front-stitcher/CMakeFiles /home/xcmg/workspace_cwx/front-stitcher/example//CMakeFiles/progress.marks
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xcmg/workspace_cwx/front-stitcher/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
example/CMakeFiles/front_stitcher_main.dir/rule:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example/CMakeFiles/front_stitcher_main.dir/rule
.PHONY : example/CMakeFiles/front_stitcher_main.dir/rule

# Convenience name for target.
front_stitcher_main: example/CMakeFiles/front_stitcher_main.dir/rule

.PHONY : front_stitcher_main

# fast build rule for target.
front_stitcher_main/fast:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/build
.PHONY : front_stitcher_main/fast

# Convenience name for target.
example/CMakeFiles/cylinder_stitcher_example.dir/rule:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example/CMakeFiles/cylinder_stitcher_example.dir/rule
.PHONY : example/CMakeFiles/cylinder_stitcher_example.dir/rule

# Convenience name for target.
cylinder_stitcher_example: example/CMakeFiles/cylinder_stitcher_example.dir/rule

.PHONY : cylinder_stitcher_example

# fast build rule for target.
cylinder_stitcher_example/fast:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/cylinder_stitcher_example.dir/build.make example/CMakeFiles/cylinder_stitcher_example.dir/build
.PHONY : cylinder_stitcher_example/fast

protobuf/image.pb.o: protobuf/image.pb.cc.o

.PHONY : protobuf/image.pb.o

# target to build an object file
protobuf/image.pb.cc.o:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/protobuf/image.pb.cc.o
.PHONY : protobuf/image.pb.cc.o

protobuf/image.pb.i: protobuf/image.pb.cc.i

.PHONY : protobuf/image.pb.i

# target to preprocess a source file
protobuf/image.pb.cc.i:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/protobuf/image.pb.cc.i
.PHONY : protobuf/image.pb.cc.i

protobuf/image.pb.s: protobuf/image.pb.cc.s

.PHONY : protobuf/image.pb.s

# target to generate assembly for a file
protobuf/image.pb.cc.s:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/protobuf/image.pb.cc.s
.PHONY : protobuf/image.pb.cc.s

protobuf/lane_line.pb.o: protobuf/lane_line.pb.cc.o

.PHONY : protobuf/lane_line.pb.o

# target to build an object file
protobuf/lane_line.pb.cc.o:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/protobuf/lane_line.pb.cc.o
.PHONY : protobuf/lane_line.pb.cc.o

protobuf/lane_line.pb.i: protobuf/lane_line.pb.cc.i

.PHONY : protobuf/lane_line.pb.i

# target to preprocess a source file
protobuf/lane_line.pb.cc.i:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/protobuf/lane_line.pb.cc.i
.PHONY : protobuf/lane_line.pb.cc.i

protobuf/lane_line.pb.s: protobuf/lane_line.pb.cc.s

.PHONY : protobuf/lane_line.pb.s

# target to generate assembly for a file
protobuf/lane_line.pb.cc.s:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/protobuf/lane_line.pb.cc.s
.PHONY : protobuf/lane_line.pb.cc.s

src/EcalImageSender.o: src/EcalImageSender.cpp.o

.PHONY : src/EcalImageSender.o

# target to build an object file
src/EcalImageSender.cpp.o:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/EcalImageSender.cpp.o
.PHONY : src/EcalImageSender.cpp.o

src/EcalImageSender.i: src/EcalImageSender.cpp.i

.PHONY : src/EcalImageSender.i

# target to preprocess a source file
src/EcalImageSender.cpp.i:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/EcalImageSender.cpp.i
.PHONY : src/EcalImageSender.cpp.i

src/EcalImageSender.s: src/EcalImageSender.cpp.s

.PHONY : src/EcalImageSender.s

# target to generate assembly for a file
src/EcalImageSender.cpp.s:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/EcalImageSender.cpp.s
.PHONY : src/EcalImageSender.cpp.s

src/FrontStitcherMain.o: src/FrontStitcherMain.cpp.o

.PHONY : src/FrontStitcherMain.o

# target to build an object file
src/FrontStitcherMain.cpp.o:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/FrontStitcherMain.cpp.o
.PHONY : src/FrontStitcherMain.cpp.o

src/FrontStitcherMain.i: src/FrontStitcherMain.cpp.i

.PHONY : src/FrontStitcherMain.i

# target to preprocess a source file
src/FrontStitcherMain.cpp.i:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/FrontStitcherMain.cpp.i
.PHONY : src/FrontStitcherMain.cpp.i

src/FrontStitcherMain.s: src/FrontStitcherMain.cpp.s

.PHONY : src/FrontStitcherMain.s

# target to generate assembly for a file
src/FrontStitcherMain.cpp.s:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/FrontStitcherMain.cpp.s
.PHONY : src/FrontStitcherMain.cpp.s

src/GstReceiver.o: src/GstReceiver.cpp.o

.PHONY : src/GstReceiver.o

# target to build an object file
src/GstReceiver.cpp.o:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/GstReceiver.cpp.o
.PHONY : src/GstReceiver.cpp.o

src/GstReceiver.i: src/GstReceiver.cpp.i

.PHONY : src/GstReceiver.i

# target to preprocess a source file
src/GstReceiver.cpp.i:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/GstReceiver.cpp.i
.PHONY : src/GstReceiver.cpp.i

src/GstReceiver.s: src/GstReceiver.cpp.s

.PHONY : src/GstReceiver.s

# target to generate assembly for a file
src/GstReceiver.cpp.s:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/GstReceiver.cpp.s
.PHONY : src/GstReceiver.cpp.s

src/Undistorter.o: src/Undistorter.cpp.o

.PHONY : src/Undistorter.o

# target to build an object file
src/Undistorter.cpp.o:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/Undistorter.cpp.o
.PHONY : src/Undistorter.cpp.o

src/Undistorter.i: src/Undistorter.cpp.i

.PHONY : src/Undistorter.i

# target to preprocess a source file
src/Undistorter.cpp.i:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/Undistorter.cpp.i
.PHONY : src/Undistorter.cpp.i

src/Undistorter.s: src/Undistorter.cpp.s

.PHONY : src/Undistorter.s

# target to generate assembly for a file
src/Undistorter.cpp.s:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/Undistorter.cpp.s
.PHONY : src/Undistorter.cpp.s

src/loguru.o: src/loguru.cpp.o

.PHONY : src/loguru.o

# target to build an object file
src/loguru.cpp.o:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/loguru.cpp.o
.PHONY : src/loguru.cpp.o

src/loguru.i: src/loguru.cpp.i

.PHONY : src/loguru.i

# target to preprocess a source file
src/loguru.cpp.i:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/loguru.cpp.i
.PHONY : src/loguru.cpp.i

src/loguru.s: src/loguru.cpp.s

.PHONY : src/loguru.s

# target to generate assembly for a file
src/loguru.cpp.s:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/loguru.cpp.s
.PHONY : src/loguru.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/cylinder_stitcher_example.dir/build.make example/CMakeFiles/cylinder_stitcher_example.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/cylinder_stitcher_example.dir/build.make example/CMakeFiles/cylinder_stitcher_example.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/cylinder_stitcher_example.dir/build.make example/CMakeFiles/cylinder_stitcher_example.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/yolo.o: src/yolo.cpp.o

.PHONY : src/yolo.o

# target to build an object file
src/yolo.cpp.o:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/yolo.cpp.o
.PHONY : src/yolo.cpp.o

src/yolo.i: src/yolo.cpp.i

.PHONY : src/yolo.i

# target to preprocess a source file
src/yolo.cpp.i:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/yolo.cpp.i
.PHONY : src/yolo.cpp.i

src/yolo.s: src/yolo.cpp.s

.PHONY : src/yolo.s

# target to generate assembly for a file
src/yolo.cpp.s:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/yolo.cpp.s
.PHONY : src/yolo.cpp.s

src/yolo_detect.o: src/yolo_detect.cpp.o

.PHONY : src/yolo_detect.o

# target to build an object file
src/yolo_detect.cpp.o:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/yolo_detect.cpp.o
.PHONY : src/yolo_detect.cpp.o

src/yolo_detect.i: src/yolo_detect.cpp.i

.PHONY : src/yolo_detect.i

# target to preprocess a source file
src/yolo_detect.cpp.i:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/yolo_detect.cpp.i
.PHONY : src/yolo_detect.cpp.i

src/yolo_detect.s: src/yolo_detect.cpp.s

.PHONY : src/yolo_detect.s

# target to generate assembly for a file
src/yolo_detect.cpp.s:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(MAKE) $(MAKESILENT) -f example/CMakeFiles/front_stitcher_main.dir/build.make example/CMakeFiles/front_stitcher_main.dir/src/yolo_detect.cpp.s
.PHONY : src/yolo_detect.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cylinder_stitcher_example"
	@echo "... front_stitcher_main"
	@echo "... protobuf/image.pb.o"
	@echo "... protobuf/image.pb.i"
	@echo "... protobuf/image.pb.s"
	@echo "... protobuf/lane_line.pb.o"
	@echo "... protobuf/lane_line.pb.i"
	@echo "... protobuf/lane_line.pb.s"
	@echo "... src/EcalImageSender.o"
	@echo "... src/EcalImageSender.i"
	@echo "... src/EcalImageSender.s"
	@echo "... src/FrontStitcherMain.o"
	@echo "... src/FrontStitcherMain.i"
	@echo "... src/FrontStitcherMain.s"
	@echo "... src/GstReceiver.o"
	@echo "... src/GstReceiver.i"
	@echo "... src/GstReceiver.s"
	@echo "... src/Undistorter.o"
	@echo "... src/Undistorter.i"
	@echo "... src/Undistorter.s"
	@echo "... src/loguru.o"
	@echo "... src/loguru.i"
	@echo "... src/loguru.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/yolo.o"
	@echo "... src/yolo.i"
	@echo "... src/yolo.s"
	@echo "... src/yolo_detect.o"
	@echo "... src/yolo_detect.i"
	@echo "... src/yolo_detect.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/xcmg/workspace_cwx/front-stitcher && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

